services:
  postgres-test-db:
    image: postgres:15
    container_name: blog_api_test_db
    environment:
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_password
      POSTGRES_DB: blog_test_db
    ports:
      # Use a different host port (e.g., 5499) to avoid conflicts with a local dev DB on 5432
      - '5499:5432'
    volumes:
      - postgres_test_data:/var/lib/postgresql/data
    healthcheck:
      # Check if the database is ready to accept connections
      test: ['CMD-SHELL', 'pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB']
      interval: 10s
      timeout: 5s
      retries: 5

# Define the named volume used above
volumes:
  postgres_test_data:
